### ISSUE TITLE
nn.KLDivLoss with nan

### ISSUE THREAD

**Issue by Eric-is-good** [DeepFakeIL/DFIL#13]
![image](https://github.com/user-attachments/assets/98dfd55a-c4fa-4066-9fc9-222a9f31da30)
in TaskN_KD.py, loss_fn_kd appear nan loss, when kl appear nan

**Comment by skyline-cpu** [comment]
Hello, I’ve also noticed the same issue, but the training results seem to be better this way. May I ask if there are still NaN values during the subsequent training?
